name: dotabuff-telegram-bot
dependencies:
- libxml2=2.9.2=0
- lxml=3.6.0=py27_0
- openssl=1.0.2g=0
- pip=8.1.1=py27_1
- python=2.7.11=0
- readline=6.2=2
- setuptools=20.6.7=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - ago==0.0.7
  - attrs==15.2.0
  - cached-property==1.3.0
  - cffi==1.5.2
  - cryptography==1.3.1
  - cssselect==0.9.1
  - enum34==1.1.2
  - idna==2.1
  - ipaddress==1.0.16
  - jdatetime==1.7.4
  - pyasn1==0.1.9
  - pyasn1-modules==0.0.8
  - pycparser==2.14
  - pyopenssl==16.0.0
  - python-dateutil==2.4.2
  - pytz==2016.3
  - pyyaml==3.11
  - queuelib==1.4.2
  - regex==2016.4.8
  - requests==2.9.1
  - scrapy==1.0.5
  - service-identity==16.0.0
  - six==1.10.0
  - telepot==6.7
  - twisted==16.1.0
  - umalqurra==0.2
  - w3lib==1.14.1
  - zope.interface==4.1.3

