name: dotabuff-telegram-bot
dependencies:
- openssl=1.0.2g=0
- pip=8.1.1=py34_1
- python=3.4.4=0
- readline=6.2=2
- setuptools=20.6.7=py34_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py34_0
- xz=5.0.5=1
- zlib=1.2.8=0

