name: dotabuff-telegram-bot
dependencies:
- libxml2=2.9.2=0
- lxml=3.6.0=py27_0
- openssl=1.0.2g=0
- pip=8.1.1=py27_1
- python=2.7.11=0
- readline=6.2=2
- setuptools=20.6.7=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - ago==0.0.7
  - attrs==15.2.0
  - awsebcli==3.7.5
  - blessed==1.9.5
  - botocore==1.4.10
  - cached-property==1.3.0
  - cement==2.8.2
  - cffi==1.5.2
  - colorama==0.3.7
  - cryptography==1.3.1
  - cssselect==0.9.1
  - docker-py==1.7.2
  - dockerpty==0.4.1
  - docopt==0.6.2
  - docutils==0.12
  - dota2api==1.3.1
  - enum34==1.1.2
  - idna==2.1
  - ipaddress==1.0.16
  - jdatetime==1.7.4
  - jmespath==0.9.0
  - meld3==1.0.2
  - pathspec==0.3.4
  - pyasn1==0.1.9
  - pyasn1-modules==0.0.8
  - pycparser==2.14
  - pyopenssl==16.0.0
  - python-dateutil==2.4.2
  - pytz==2016.3
  - pyyaml==3.11
  - queuelib==1.4.2
  - regex==2016.4.8
  - requests==2.9.1
  - scrapy==1.0.5
  - semantic-version==2.5.0
  - service-identity==16.0.0
  - six==1.10.0
  - supervisor==3.2.3
  - telepot==6.7
  - texttable==0.8.4
  - twisted==16.1.0
  - umalqurra==0.2
  - w3lib==1.14.1
  - wcwidth==0.1.6
  - websocket-client==0.35.0
  - zope.interface==4.1.3

