STEAM_API_KEY = 'A7D42505EDFFE0281AD36026469FD9D0'
STEAM_DOMAIN_NAME = 'elasticbeanstalk.com'
BOT_TOKEN = "217953455:AAFnirch6J-nAquAg7wb_vWklPno_5hE_7U"

DOTABUFF_URL = 'http://www.dotabuff.com/'
DEFAULT_NAMES = ['Puppey', 'Dendi', 'Atomic', 'HappyMeds']
PLAYERS_CUTOFF = 10
MATCHES_CUTOFF = 2

VIP_PLAYERS_IDS = {
    u'Atomic': u'116845505',
    u'HappyMeds': u'163519691',
    u'Shark': u'123652141',
    u'Exelens': u'Exelens',  # 91363115
}

HEROES_DATA = {
    1: (u'Anti-Mage', u'http://cdn.dota2.com/apps/dota2/images/heroes/antimage_sb.png'),
    2: (u'Axe', u'http://cdn.dota2.com/apps/dota2/images/heroes/axe_sb.png'),
    3: (u'Bane', u'http://cdn.dota2.com/apps/dota2/images/heroes/bane_sb.png'),
    4: (u'Bloodseeker', u'http://cdn.dota2.com/apps/dota2/images/heroes/bloodseeker_sb.png'),
    5: (u'Crystal Maiden', u'http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_sb.png'),
    6: (u'Drow Ranger', u'http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_sb.png'),
    7: (u'Earthshaker', u'http://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_sb.png'),
    8: (u'Juggernaut', u'http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_sb.png'),
    9: (u'Mirana', u'http://cdn.dota2.com/apps/dota2/images/heroes/mirana_sb.png'),
    10: (u'Morphling', u'http://cdn.dota2.com/apps/dota2/images/heroes/morphling_sb.png'),
    11: (u'Shadow Fiend', u'http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_sb.png'),
    12: (u'Phantom Lancer', u'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_lancer_sb.png'),
    13: (u'Puck', u'http://cdn.dota2.com/apps/dota2/images/heroes/puck_sb.png'),
    14: (u'Pudge', u'http://cdn.dota2.com/apps/dota2/images/heroes/pudge_sb.png'),
    15: (u'Razor', u'http://cdn.dota2.com/apps/dota2/images/heroes/razor_sb.png'),
    16: (u'Sand King', u'http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_sb.png'),
    17: (u'Storm Spirit', u'http://cdn.dota2.com/apps/dota2/images/heroes/storm_spirit_sb.png'),
    18: (u'Sven', u'http://cdn.dota2.com/apps/dota2/images/heroes/sven_sb.png'),
    19: (u'Tiny', u'http://cdn.dota2.com/apps/dota2/images/heroes/tiny_sb.png'),
    20: (u'Vengeful Spirit', u'http://cdn.dota2.com/apps/dota2/images/heroes/vengefulspirit_sb.png'),
    21: (u'Windranger', u'http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_sb.png'),
    22: (u'Zeus', u'http://cdn.dota2.com/apps/dota2/images/heroes/zuus_sb.png'),
    23: (u'Kunkka', u'http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_sb.png'),
    25: (u'Lina', u'http://cdn.dota2.com/apps/dota2/images/heroes/lina_sb.png'),
    26: (u'Lion', u'http://cdn.dota2.com/apps/dota2/images/heroes/lion_sb.png'),
    27: (u'Shadow Shaman', u'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_sb.png'),
    28: (u'Slardar', u'http://cdn.dota2.com/apps/dota2/images/heroes/slardar_sb.png'),
    29: (u'Tidehunter', u'http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_sb.png'),
    30: (u'Witch Doctor', u'http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_sb.png'),
    31: (u'Lich', u'http://cdn.dota2.com/apps/dota2/images/heroes/lich_sb.png'),
    32: (u'Riki', u'http://cdn.dota2.com/apps/dota2/images/heroes/riki_sb.png'),
    33: (u'Enigma', u'http://cdn.dota2.com/apps/dota2/images/heroes/enigma_sb.png'),
    34: (u'Tinker', u'http://cdn.dota2.com/apps/dota2/images/heroes/tinker_sb.png'),
    35: (u'Sniper', u'http://cdn.dota2.com/apps/dota2/images/heroes/sniper_sb.png'),
    36: (u'Necrophos', u'http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_sb.png'),
    37: (u'Warlock', u'http://cdn.dota2.com/apps/dota2/images/heroes/warlock_sb.png'),
    38: (u'Beastmaster', u'http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_sb.png'),
    39: (u'Queen of Pain', u'http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_sb.png'),
    40: (u'Venomancer', u'http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_sb.png'),
    41: (u'Faceless Void', u'http://cdn.dota2.com/apps/dota2/images/heroes/faceless_void_sb.png'),
    42: (u'Wraith King', u'http://cdn.dota2.com/apps/dota2/images/heroes/skeleton_king_sb.png'),
    43: (u'Death Prophet', u'http://cdn.dota2.com/apps/dota2/images/heroes/death_prophet_sb.png'),
    44: (u'Phantom Assassin', u'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_sb.png'),
    45: (u'Pugna', u'http://cdn.dota2.com/apps/dota2/images/heroes/pugna_sb.png'),
    46: (u'Templar Assassin', u'http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_sb.png'),
    47: (u'Viper', u'http://cdn.dota2.com/apps/dota2/images/heroes/viper_sb.png'),
    48: (u'Luna', u'http://cdn.dota2.com/apps/dota2/images/heroes/luna_sb.png'),
    49: (u'Dragon Knight', u'http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_sb.png'),
    50: (u'Dazzle', u'http://cdn.dota2.com/apps/dota2/images/heroes/dazzle_sb.png'),
    51: (u'Clockwerk', u'http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_sb.png'),
    52: (u'Leshrac', u'http://cdn.dota2.com/apps/dota2/images/heroes/leshrac_sb.png'),
    53: (u"Nature's Prophet", u'http://cdn.dota2.com/apps/dota2/images/heroes/furion_sb.png'),
    54: (u'Lifestealer', u'http://cdn.dota2.com/apps/dota2/images/heroes/life_stealer_sb.png'),
    55: (u'Dark Seer', u'http://cdn.dota2.com/apps/dota2/images/heroes/dark_seer_sb.png'),
    56: (u'Clinkz', u'http://cdn.dota2.com/apps/dota2/images/heroes/clinkz_sb.png'),
    57: (u'Omniknight', u'http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_sb.png'),
    58: (u'Enchantress', u'http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_sb.png'),
    59: (u'Huskar', u'http://cdn.dota2.com/apps/dota2/images/heroes/huskar_sb.png'),
    60: (u'Night Stalker', u'http://cdn.dota2.com/apps/dota2/images/heroes/night_stalker_sb.png'),
    61: (u'Broodmother', u'http://cdn.dota2.com/apps/dota2/images/heroes/broodmother_sb.png'),
    62: (u'Bounty Hunter', u'http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_sb.png'),
    63: (u'Weaver', u'http://cdn.dota2.com/apps/dota2/images/heroes/weaver_sb.png'),
    64: (u'Jakiro', u'http://cdn.dota2.com/apps/dota2/images/heroes/jakiro_sb.png'),
    65: (u'Batrider', u'http://cdn.dota2.com/apps/dota2/images/heroes/batrider_sb.png'),
    66: (u'Chen', u'http://cdn.dota2.com/apps/dota2/images/heroes/chen_sb.png'),
    67: (u'Spectre', u'http://cdn.dota2.com/apps/dota2/images/heroes/spectre_sb.png'),
    68: (u'Ancient Apparition', u'http://cdn.dota2.com/apps/dota2/images/heroes/ancient_apparition_sb.png'),
    69: (u'Doom', u'http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_sb.png'),
    70: (u'Ursa', u'http://cdn.dota2.com/apps/dota2/images/heroes/ursa_sb.png'),
    71: (u'Spirit Breaker', u'http://cdn.dota2.com/apps/dota2/images/heroes/spirit_breaker_sb.png'),
    72: (u'Gyrocopter', u'http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_sb.png'),
    73: (u'Alchemist', u'http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_sb.png'),
    74: (u'Invoker', u'http://cdn.dota2.com/apps/dota2/images/heroes/invoker_sb.png'),
    75: (u'Silencer', u'http://cdn.dota2.com/apps/dota2/images/heroes/silencer_sb.png'),
    76: (u'Outworld Devourer', u'http://cdn.dota2.com/apps/dota2/images/heroes/obsidian_destroyer_sb.png'),
    77: (u'Lycan', u'http://cdn.dota2.com/apps/dota2/images/heroes/lycan_sb.png'),
    78: (u'Brewmaster', u'http://cdn.dota2.com/apps/dota2/images/heroes/brewmaster_sb.png'),
    79: (u'Shadow Demon', u'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_demon_sb.png'),
    80: (u'Lone Druid', u'http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_sb.png'),
    81: (u'Chaos Knight', u'http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_sb.png'),
    82: (u'Meepo', u'http://cdn.dota2.com/apps/dota2/images/heroes/meepo_sb.png'),
    83: (u'Treant Protector', u'http://cdn.dota2.com/apps/dota2/images/heroes/treant_sb.png'),
    84: (u'Ogre Magi', u'http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_sb.png'),
    85: (u'Undying', u'http://cdn.dota2.com/apps/dota2/images/heroes/undying_sb.png'),
    86: (u'Rubick', u'http://cdn.dota2.com/apps/dota2/images/heroes/rubick_sb.png'),
    87: (u'Disruptor', u'http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_sb.png'),
    88: (u'Nyx Assassin', u'http://cdn.dota2.com/apps/dota2/images/heroes/nyx_assassin_sb.png'),
    89: (u'Naga Siren', u'http://cdn.dota2.com/apps/dota2/images/heroes/naga_siren_sb.png'),
    90: (u'Keeper of the Light', u'http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_sb.png'),
    91: (u'Io', u'http://cdn.dota2.com/apps/dota2/images/heroes/wisp_sb.png'),
    92: (u'Visage', u'http://cdn.dota2.com/apps/dota2/images/heroes/visage_sb.png'),
    93: (u'Slark', u'http://cdn.dota2.com/apps/dota2/images/heroes/slark_sb.png'),
    94: (u'Medusa', u'http://cdn.dota2.com/apps/dota2/images/heroes/medusa_sb.png'),
    95: (u'Troll Warlord', u'http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_sb.png'),
    96: (u'Centaur Warrunner', u'http://cdn.dota2.com/apps/dota2/images/heroes/centaur_sb.png'),
    97: (u'Magnus', u'http://cdn.dota2.com/apps/dota2/images/heroes/magnataur_sb.png'),
    98: (u'Timbersaw', u'http://cdn.dota2.com/apps/dota2/images/heroes/shredder_sb.png'),
    99: (u'Bristleback', u'http://cdn.dota2.com/apps/dota2/images/heroes/bristleback_sb.png'),
    100: (u'Tusk', u'http://cdn.dota2.com/apps/dota2/images/heroes/tusk_sb.png'),
    101: (u'Skywrath Mage', u'http://cdn.dota2.com/apps/dota2/images/heroes/skywrath_mage_sb.png'),
    102: (u'Abaddon', u'http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_sb.png'),
    103: (u'Elder Titan', u'http://cdn.dota2.com/apps/dota2/images/heroes/elder_titan_sb.png'),
    104: (u'Legion Commander', u'http://cdn.dota2.com/apps/dota2/images/heroes/legion_commander_sb.png'),
    105: (u'Techies', u'http://cdn.dota2.com/apps/dota2/images/heroes/techies_sb.png'),
    106: (u'Ember Spirit', u'http://cdn.dota2.com/apps/dota2/images/heroes/ember_spirit_sb.png'),
    107: (u'Earth Spirit', u'http://cdn.dota2.com/apps/dota2/images/heroes/earth_spirit_sb.png'),
    109: (u'Terrorblade', u'http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_sb.png'),
    110: (u'Phoenix', u'http://cdn.dota2.com/apps/dota2/images/heroes/phoenix_sb.png'),
    111: (u'Oracle', u'http://cdn.dota2.com/apps/dota2/images/heroes/oracle_sb.png'),
    112: (u'Winter Wyvern', u'http://cdn.dota2.com/apps/dota2/images/heroes/winter_wyvern_sb.png'),
    113: (u'Arc Warden', u'http://cdn.dota2.com/apps/dota2/images/heroes/arc_warden_sb.png')
}
